# Generated by Django 3.2.4 on 2021-07-12 17:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0002_alter_credential_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
