# Generated by Django 3.2.4 on 2021-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0004_alter_credential_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='credential',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
